import {
  Wifi,
  Snowflake,
  Utensils,
  Droplet,
  Leaf,
  CookingPot,
  Eye,
  BedSingle,
  BedDouble,
  Bed,
  Soup,
  Footprints,
  LampDesk,
  CurlyBraces,
} from "lucide-react";

export const amenityIcons: Record<string, React.ReactNode> = {
  "Free Wi-Fi": <Wifi />,
  "Air conditioning": <Snowflake />,
  "Private outdoor dining area": <Utensils />,
  "Private outdoor dining table": <Utensils />,
  "Shared bathroom with shower": <Droplet />,
  "Shared bathroom and shower": <Droplet />,
  "Shared bathroom with hot shower": <Droplet />,
  "Toiletries and towels": <Soup />,
  "Towels and toiletries provided": <Soup />,
  "Access to vegetable garden": <Leaf />,
  "Home-cooked meals available": <CookingPot />,
  "Optional home-cooked meals": <CookingPot />,
  "Cooking equipment provided": <CookingPot />,
  "Cook your own veggies with provided tools": <CookingPot />,
  "King-sized bed": <Bed />,
  "Queen-sized bed": <BedDouble />,
  "Single bed with quality linens": <BedSingle />,
  "2-layer windproof curtains": <CurlyBraces />,
  "Windproof curtains": <CurlyBraces />,
  "Overlooking rice fields and farm plots": <Eye />,
  "Panoramic views of the surrounding rice fields and vegetable gardens": <Eye />,
  "Access to swings and hiking trail": <Footprints />,
  "Desk and reading lamp": <LampDesk />,
  "Quiet surroundings with garden view": <Leaf />,
};
